-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\fpga_fir_test\ir_filter.vhd
-- Created: 2022-04-25 23:07:42
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 8.13802e-09
-- Target subsystem base rate: 8.13802e-09
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        8.13802e-09
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- data_out                      ce_out        8.13802e-09
-- data_out_valid                ce_out        8.13802e-09
-- data_in_ready                 ce_out        8.13802e-09
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ir_filter
-- Source Path: fpga_fir_test/ir_filter
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ir_filter IS
  PORT( i_clk_dsp_122M88                  :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        data_in                           :   IN    signed(23 DOWNTO 0);  -- sfix24_En15
        data_in_valid                     :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        data_out                          :   OUT   signed(23 DOWNTO 0);  -- sfix24_En15
        data_out_valid                    :   OUT   std_logic;
        data_in_ready                     :   OUT   std_logic
        );
END ir_filter;


ARCHITECTURE rtl OF ir_filter IS

  -- Component Declarations
  COMPONENT fir_filter_hdl
    PORT( i_clk_dsp_122M88                :   IN    std_logic;
          reset                           :   IN    std_logic;
          en                              :   IN    std_logic;
          en_1_1_1                        :   IN    std_logic;
          dataIn                          :   IN    signed(23 DOWNTO 0);  -- sfix24_En15
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   signed(43 DOWNTO 0);  -- sfix44_En30
          validOut                        :   OUT   std_logic;
          ready                           :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT s_and_h
    PORT( i_clk_dsp_122M88                :   IN    std_logic;
          reset                           :   IN    std_logic;
          en                              :   IN    std_logic;
          In_rsvd                         :   IN    signed(43 DOWNTO 0);  -- sfix44_En30
          Trigger                         :   IN    std_logic;
          alpha                           :   OUT   signed(43 DOWNTO 0)  -- sfix44_En30
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : fir_filter_hdl
    USE ENTITY work.fir_filter_hdl(rtl);

  FOR ALL : s_and_h
    USE ENTITY work.s_and_h(rtl);

  -- Signals
  SIGNAL en                               : std_logic;
  SIGNAL w_data_in                        : signed(23 DOWNTO 0);  -- sfix24_En15
  SIGNAL w_data_in_valid                  : std_logic;
  SIGNAL w_data_in_1                      : signed(23 DOWNTO 0) := (OTHERS => '0');  -- sfix24_En15
  SIGNAL w_data_in_valid_1                : std_logic := '0';
  SIGNAL fir_filter_hdl_out1              : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL w_data_out_valid                 : std_logic;
  SIGNAL fir_filter_hdl_out3              : std_logic;
  SIGNAL fir_filter_hdl_out1_1            : signed(43 DOWNTO 0) := (OTHERS => '0');  -- sfix44_En30
  SIGNAL w_data_out_valid_1               : std_logic := '0';
  SIGNAL s_and_h_out1                     : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL Extract_Bits_out1                : signed(23 DOWNTO 0);  -- sfix24_En10
  SIGNAL Data_Type_Conversion_out1        : signed(23 DOWNTO 0);  -- sfix24_En15
  SIGNAL fir_filter_hdl_out3_1            : std_logic := '0';

BEGIN
  u_fir_filter_hdl : fir_filter_hdl
    PORT MAP( i_clk_dsp_122M88 => i_clk_dsp_122M88,
              reset => reset,
              en => clk_enable,
              en_1_1_1 => clk_enable,
              dataIn => w_data_in_1,  -- sfix24_En15
              validIn => w_data_in_valid_1,
              dataOut => fir_filter_hdl_out1,  -- sfix44_En30
              validOut => w_data_out_valid,
              ready => fir_filter_hdl_out3
              );

  u_s_and_h : s_and_h
    PORT MAP( i_clk_dsp_122M88 => i_clk_dsp_122M88,
              reset => reset,
              en => clk_enable,
              In_rsvd => fir_filter_hdl_out1_1,  -- sfix44_En30
              Trigger => w_data_out_valid_1,
              alpha => s_and_h_out1  -- sfix44_En30
              );

  w_data_in <= data_in;

  w_data_in_valid <= data_in_valid;

  en <= clk_enable;

  fir_filter_hdl_in0_buff_in_pipe_process : PROCESS (i_clk_dsp_122M88)
  BEGIN
    IF i_clk_dsp_122M88'EVENT AND i_clk_dsp_122M88 = '1' THEN
      IF en = '1' THEN
        w_data_in_1 <= w_data_in;
      END IF;
    END IF;
  END PROCESS fir_filter_hdl_in0_buff_in_pipe_process;


  fir_filter_hdl_in1_buff_in_pipe_process : PROCESS (i_clk_dsp_122M88)
  BEGIN
    IF i_clk_dsp_122M88'EVENT AND i_clk_dsp_122M88 = '1' THEN
      IF en = '1' THEN
        w_data_in_valid_1 <= w_data_in_valid;
      END IF;
    END IF;
  END PROCESS fir_filter_hdl_in1_buff_in_pipe_process;


  fir_filter_hdl_out2_buff_out_pipe_process : PROCESS (i_clk_dsp_122M88)
  BEGIN
    IF i_clk_dsp_122M88'EVENT AND i_clk_dsp_122M88 = '1' THEN
      IF en = '1' THEN
        fir_filter_hdl_out1_1 <= fir_filter_hdl_out1;
      END IF;
    END IF;
  END PROCESS fir_filter_hdl_out2_buff_out_pipe_process;


  fir_filter_hdl_out3_buff_out_pipe_process : PROCESS (i_clk_dsp_122M88)
  BEGIN
    IF i_clk_dsp_122M88'EVENT AND i_clk_dsp_122M88 = '1' THEN
      IF en = '1' THEN
        w_data_out_valid_1 <= w_data_out_valid;
      END IF;
    END IF;
  END PROCESS fir_filter_hdl_out3_buff_out_pipe_process;


  Extract_Bits_out1 <= signed(s_and_h_out1(43 DOWNTO 20));

  Data_Type_Conversion_out1 <= Extract_Bits_out1;

  fir_filter_hdl_out4_buff_out_pipe_process : PROCESS (i_clk_dsp_122M88)
  BEGIN
    IF i_clk_dsp_122M88'EVENT AND i_clk_dsp_122M88 = '1' THEN
      IF en = '1' THEN
        fir_filter_hdl_out3_1 <= fir_filter_hdl_out3;
      END IF;
    END IF;
  END PROCESS fir_filter_hdl_out4_buff_out_pipe_process;


  ce_out <= clk_enable;

  data_out <= Data_Type_Conversion_out1;

  data_out_valid <= w_data_out_valid_1;

  data_in_ready <= fir_filter_hdl_out3_1;

END rtl;

