-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\fpga_fir_test\s_and_h.vhd
-- Created: 2022-05-04 15:57:52
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: s_and_h
-- Source Path: fpga_fir_test/ir_filter/s_and_h
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY s_and_h IS
  PORT( i_clk_dsp_122M88                  :   IN    std_logic;
        reset                             :   IN    std_logic;
        en                                :   IN    std_logic;
        In_rsvd                           :   IN    signed(35 DOWNTO 0);  -- sfix36_En30
        Trigger                           :   IN    std_logic;
        alpha                             :   OUT   signed(35 DOWNTO 0)  -- sfix36_En30
        );
END s_and_h;


ARCHITECTURE rtl OF s_and_h IS

  -- Signals
  SIGNAL en_gated                         : std_logic;
  SIGNAL Trigger_delayed                  : std_logic := '1';
  SIGNAL Trigger_emulated                 : std_logic;
  SIGNAL In_bypass                        : signed(35 DOWNTO 0);  -- sfix36_En30
  SIGNAL In_last_value                    : signed(35 DOWNTO 0) := (OTHERS => '0');  -- sfix36_En30

BEGIN

  Trigger_delay_process: PROCESS (i_clk_dsp_122M88)
  BEGIN
    IF i_clk_dsp_122M88'event AND i_clk_dsp_122M88 = '1' THEN
      IF en = '1' THEN
        Trigger_delayed <= Trigger;
      END IF;
    END IF;
  END PROCESS Trigger_delay_process;

  Trigger_emulated <= NOT Trigger_delayed AND Trigger;

  en_gated <= Trigger_emulated AND en;

  alpha_bypass_process : PROCESS (i_clk_dsp_122M88)
  BEGIN
    IF i_clk_dsp_122M88'EVENT AND i_clk_dsp_122M88 = '1' THEN
      IF en_gated = '1' THEN
        In_last_value <= In_bypass;
      END IF;
    END IF;
  END PROCESS alpha_bypass_process;


  
  In_bypass <= In_last_value WHEN Trigger_emulated = '0' ELSE
      In_rsvd;

  alpha <= In_bypass;

END rtl;

